### ISSUE TITLE
Stopping and starting the server and keep devices persistent.

### ISSUE THREAD

**Issue by swttt** [abedinpour/HAS#2]
When Stopping the server and then starting again, i can't reach any of my devices.
But do see multiple logs coming in:

```
Homekit server starting!
HTTP Server Listening on 46089
TCP Server Listening on 8090
Bonjour is up
Bonjour stopped
HTTP stopped
TCP stopped
Eettafel
LIGHT: Found capability ONOFF
LIGHT: Found capability DIM
Eettafel is added!
HTTP Server Listening on 41063
HTTP Server Listening on 41063
TCP Server Listening on 8090
TCP Server Listening on 8090
TCP Server Listening on 8090
TCP Server Listening on 8090
```

**Comment by swttt** [comment]
Expected to being able to just use `server.startServer()` but it has to go trough all the config options again. So running trough them again it works as expected.

**Comment by swttt** [comment]
Still having troubles keeping devices/pairings persistent.
I'll change the issue title for this.

When stop the server and then start it again, by just running `server.stopServer()` and `server.startServer()` it is unable to connect and gives the result as above.

When i start the server with all the config options again, it works...but the devices get re-added and are added to the main "Room" zone. Where a normal app restart the devices get added again as well, but in the room they are added to.

**Comment by mhabedinpour** [comment]
I'll fix the restart problem.
About devices problem, as i see in your source code you are using a global variable for keeping IDs and each time you add a new device, you `++` this variable.
You need to reset this variable before starting the server again, or use a better solution for keeping IDs. Because if IDs change for any other reason, you will face with similar problems.

**Comment by swttt** [comment]
Ye i know 😀 Working on a solution for that. Actually my devices already have an UID, but it seems that can't be used for the HAS ids.

**Comment by mhabedinpour** [comment]
I'll add a helper to map your UIDs to HAS IDs.

**Comment by swttt** [comment]
Oeh, awesome! :smile:

Any chance i could force some kind of update when a device is added? Now sometimes it takes around 15 sec or longer before it shows up in homekit.

EDIT: I meant UUID btw.. Example of the device id is `d2ecac72-9390-4ff1-b0fd-de3b56753b51`. As far as i know it's impossible to convert this to an INT. But i could be wrong of course :smile:

**Comment by mhabedinpour** [comment]
`HAS.stopServer()` is fixed now and a callback is added to it.
```JS
server.stopServer(() => {
   console.log('stopped');
   server.startServer();
});
```

**Comment by mhabedinpour** [comment]
You are absolutely right. We can't convert UUID to integer, Because UUID is 128bit and integer is 32bit(or 64bit). But as i said we can use a map.
I'm going to close this issue and open another one for UUID helper.
