### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by FrankDoersam** [abedinpour/HAS#6]
Hello Abedinpour, I saw her project with HomeKit on Github, thank you :)

**Comment by mhabedinpour** [comment]
Hey,
Thanks. Glad you liked it.

**Comment by FrankDoersam** [comment]
I would be very keen to publish such an opportunity in .net (c #) as an open source. However, I can not access the Apple spec. Would you be interested in supporting the project or briefly explaining the process (required techniques)?

**Comment by mhabedinpour** [comment]
I can't post the HAP specification here, But if you give me your email address, I can mail it to you.

**Comment by FrankDoersam** [comment]
frank@familiedoersam.de
Thanks!

**Comment by FrankDoersam** [comment]
Would you be interested or able to help develop a C # solution? :)
